from __future__ import annotations

import unittest

from fastapi.testclient import TestClient

from app import app


class DevRoutesStaticTests(unittest.TestCase):
    def test_dev_redesign_routes_are_available(self) -> None:
        client = TestClient(app)

        routes = {
            "/dev": "OpenAI Ads 운영 워크벤치",
            "/dev/admin": "OpenAI Ads 운영 관리자 콘솔",
            "/dev/creative-upload-draft": "소재 접수 및 업로드 워크북 생성",
        }
        for path, phrase in routes.items():
            with self.subTest(path=path):
                response = client.get(path)
                self.assertEqual(response.status_code, 200)
                self.assertIn(phrase, response.text)
                self.assertIn('/dev-assets/dev-redesign.css', response.text)
                self.assertIn("@tabler/core", response.text)

    def test_dev_pages_use_new_command_center_markup(self) -> None:
        client = TestClient(app)

        home = client.get("/dev").text
        admin = client.get("/dev/admin").text
        intake = client.get("/dev/creative-upload-draft").text

        self.assertIn('class="app-frame"', home)
        self.assertIn('data-view-button="qa"', home)
        self.assertIn('id="workspace-layout"', home)
        self.assertIn("is-wide-mode", home)
        self.assertIn("faqCategories", home)
        self.assertIn("광고 정책 및 운영 FAQ", home)
        self.assertIn("Account Spend Cap", home)
        self.assertIn("renderFaq", home)
        self.assertIn("data-faq-category", home)
        self.assertIn("data-faq-id", home)
        self.assertIn("캠페인 영향", home)
        self.assertIn("landingCampaignImpact", home)
        self.assertIn("faviconCampaignImpact", home)
        self.assertIn("campaign_impact", home)
        self.assertIn("guide-tabs", home)
        self.assertIn("data-guide-deck=\"advertiser\"", home)
        self.assertIn("data-guide-deck=\"setup\"", home)
        self.assertIn("data-guide-deck=\"pixel\"", home)
        self.assertIn("dev-slide-deck", home)
        self.assertIn("printCurrentGuideDeck", home)
        self.assertIn("applyGuideLayout", home)
        self.assertIn("guideDeckDefaults", home)
        self.assertIn("GUIDE_LAYOUT_VERSION = 4", home)
        self.assertIn("광고 카피 작성 가이드", home)
        self.assertIn("플래너에게 받아야 할 캠페인 정보 및 소재", home)
        self.assertIn("OpenAI 공식 워크북 기준", home)
        self.assertIn("정식 오픈 시 Ads Manager 재확인", home)
        self.assertIn("dev-card-code", home)
        self.assertIn("campaign_preview", home)
        self.assertIn("STEP 3-C · 맞춤 이벤트 & QA", home)
        self.assertIn("pixel_step6_event_list", home)
        self.assertIn("GTM 컨테이너 ID", home)
        self.assertIn('id="admin-app"', admin)
        self.assertIn("echarts@5", admin)
        self.assertIn('id="notice-toolbar"', admin)
        self.assertIn('id="notice-editor"', admin)
        self.assertIn('contenteditable="true"', admin)
        self.assertIn("data-notice-command", admin)
        self.assertIn("data-notice-format", admin)
        self.assertIn("data-notice-template", admin)
        self.assertIn('id="notice-preview-body"', admin)
        self.assertNotIn('id="notice-body"', admin)
        self.assertNotIn("본문 HTML", admin)
        self.assertIn('id="analytics-period"', admin)
        self.assertIn("analytics-chart-grid", admin)
        self.assertIn('id="visit-pie-chart"', admin)
        self.assertIn('id="analytics-page-rows"', admin)
        self.assertIn('id="analytics-download-rows"', admin)
        self.assertIn("질문 카테고리", admin)
        self.assertIn('id="question-category-list"', admin)
        self.assertIn("data-question-category", admin)
        self.assertIn('id="admin-guide-tabs"', admin)
        self.assertIn('id="admin-guide-deck"', admin)
        self.assertIn("data-admin-guide-deck=\"advertiser\"", admin)
        self.assertIn("data-admin-guide-deck=\"setup\"", admin)
        self.assertIn("data-admin-guide-deck=\"pixel\"", admin)
        self.assertIn("adminGuideDecks", admin)
        self.assertIn("normalizeAdminGuideDeckEditKeys", admin)
        self.assertIn("guide-editable-text", admin)
        self.assertIn("data-guide-text-key", admin)
        self.assertIn("data-guide-image-key", admin)
        self.assertIn('id="add-admin-guide-slide"', admin)
        self.assertIn('data-guide-action="add-card"', admin)
        self.assertIn('data-guide-action="remove-card"', admin)
        self.assertIn('data-guide-action="move-slide-up"', admin)
        self.assertIn('data-guide-action="move-slide-down"', admin)
        self.assertIn('data-guide-action="remove-slide"', admin)
        self.assertIn("guideLayoutPayload", admin)
        self.assertIn("applyAdminGuideLayout", admin)
        self.assertIn("collectGuidePayloadKeys", admin)
        self.assertIn("hydrateGuidePayloadItems", admin)
        self.assertIn("GUIDE_LAYOUT_VERSION = 4", admin)
        self.assertIn("광고 카피 작성 가이드", admin)
        self.assertIn("플래너에게 받아야 할 캠페인 정보 및 소재", admin)
        self.assertIn("OpenAI 공식 워크북 기준", admin)
        self.assertIn("정식 오픈 시 Ads Manager 재확인", admin)
        self.assertIn("STEP 3-C · 맞춤 이벤트 & QA", admin)
        self.assertIn("pixel_step6_event_list", admin)
        self.assertIn("codeBlocks", admin)
        self.assertIn("kickerKey", admin)
        self.assertNotIn("이미지 URL 교체", admin)
        self.assertNotIn("admin-guide-image-url", admin)
        self.assertIn("admin-guide-image-file", admin)
        self.assertIn("uploadGuideImageFile", admin)
        self.assertIn("/api/admin/guide-image", admin)
        self.assertIn("setButtonBusy", admin)
        self.assertIn("button-spinner", admin)
        self.assertIn("안내자료 저장이 완료되었습니다.", admin)
        self.assertIn("readGuidePayload", admin)
        self.assertNotIn('id="guide-item-editor"', admin)
        self.assertNotIn('id="guide-image-editor"', admin)
        self.assertIn('id="ads-key-search"', admin)
        self.assertIn('id="ads-key-sort"', admin)
        self.assertIn('id="ads-key-prev"', admin)
        self.assertIn('id="ads-key-next"', admin)
        self.assertIn('id="cancel-ads-edit"', admin)
        self.assertIn("ADS_KEY_PAGE_SIZE = 10", admin)
        self.assertIn("renderAdsKeyRows", admin)
        self.assertIn("editAdsKey", admin)
        self.assertIn("deleteAdsKey", admin)
        self.assertIn('data-ads-action="edit"', admin)
        self.assertIn('data-ads-action="delete"', admin)
        self.assertIn('id="campaign-template"', intake)
        self.assertIn('id="adgroup-template"', intake)
        self.assertIn("수동 국가", intake)
        self.assertIn("캠페인 입력 요약", intake)
        self.assertIn("광고그룹 입력 요약", intake)
        self.assertIn("소재 입력 요약", intake)
        self.assertIn("campaign_name 자동 참조", intake)
        self.assertIn("adgroup_name 자동 참조", intake)
        self.assertIn("summary-ad-name", intake)
        self.assertIn("summary-ad-link", intake)
        self.assertIn("수동 입찰가", intake)
        self.assertIn("campaign-manual-country", intake)
        self.assertIn("adgroup-manual-bid", intake)
        self.assertIn("collapse-toggle", intake)
        self.assertIn('class="btn-plain add-campaign"', intake)
        self.assertIn('class="btn-plain add-adgroup"', intake)
        self.assertIn('class="btn-plain add-ad"', intake)
        self.assertIn("소재그룹 추가", intake)
        self.assertIn("insertAfter.after", intake)
        self.assertIn("campaign-sequence", intake)
        self.assertIn("adgroup-sequence", intake)
        self.assertIn("ad-sequence", intake)
        self.assertIn("campaignThemes", intake)
        self.assertIn("applyCampaignTheme", intake)
        self.assertIn("validateNameFields", intake)
        self.assertIn("validateDerivedFields", intake)
        self.assertIn("캠페인 1", intake)
        self.assertIn("광고그룹 1-1", intake)
        self.assertIn("소재 1-1-1", intake)
        self.assertIn("workbook-notice", intake)
        self.assertIn("다운로드한 XLSX는 OpenAI Ads Manager 벌크 업로드 기준 파일입니다.", intake)
        self.assertIn("serverErrorMessage", intake)
        self.assertIn("isSafeWorkbookName", intake)
        self.assertIn("isHttpUrl", intake)
        self.assertIn("campaignBlocks().map(readCampaign)", intake)
        self.assertIn("data-reference-static", intake)
        self.assertIn("한글, 영문, 숫자", intake)
        self.assertIn("review-overlay", intake)
        self.assertIn("구글 시트에 저장할 내용을 확인해 주세요", intake)
        self.assertIn("openReviewModal(payload())", intake)
        self.assertIn("manual_target_country", intake)
        self.assertIn("manual_target_country_label", intake)
        self.assertIn("manual_max_bid", intake)
        self.assertIn("수동 입찰가(KRW)", intake)
        self.assertIn("submitReviewedPayload", intake)
        self.assertIn("pendingSubmissionPayload", intake)
        self.assertIn("required-mark", intake)
        self.assertIn("Ads Manager Reference", intake)
        self.assertIn("실제 세팅 창 참고", intake)
        self.assertIn("표준 캠페인", intake)
        self.assertIn("제품피드 캠페인", intake)
        self.assertIn("아직 비활성", intake)
        self.assertIn("제품 피드 ID", intake)
        self.assertIn("새 캠페인 · 캠페인 만들기", intake)
        self.assertIn("광고그룹 만들기", intake)
        self.assertIn("광고 만들기 · 광고 소재", intake)
        self.assertIn("전환 이벤트(선택 사항)", intake)
        self.assertIn("종료일 설정", intake)
        self.assertIn("다음: 광고 그룹", intake)
        self.assertIn("최대 CPC 입찰가", intake)
        self.assertIn("컨텍스트 힌트", intake)
        self.assertIn("광고 이미지", intake)
        self.assertIn('<option value="ALL">전체</option>', intake)
        self.assertIn('<option value="US">미국</option>', intake)
        self.assertIn('<option value="AU">오스트레일리아</option>', intake)
        self.assertIn('<option value="CA">캐나다</option>', intake)
        self.assertIn('<option value="JP">일본</option>', intake)
        self.assertIn('<option value="NZ">뉴질랜드</option>', intake)
        self.assertIn('<option value="KR">대한민국</option>', intake)
        self.assertIn('<option value="GB">영국</option>', intake)
        self.assertNotIn("Ads Manager 계정 준비", intake)
        self.assertNotIn("정산 정보 확인", intake)
        self.assertNotIn("랜딩 접근 확인", intake)
        self.assertNotIn("로고·파비콘 확인", intake)
        self.assertNotIn("대한민국은 수동 세팅에서는 선택하고", intake)
        self.assertNotIn("xlsx target_countries", intake)
        self.assertNotIn("xlsx max_bid", intake)
        self.assertNotIn('id="add-campaign"', intake)
        self.assertNotIn('$("#add-campaign")', intake)

    def test_dev_redesign_css_asset_is_available(self) -> None:
        client = TestClient(app)

        response = client.get("/dev-assets/dev-redesign.css")

        self.assertEqual(response.status_code, 200)
        self.assertIn("text/css", response.headers.get("content-type", ""))
        self.assertIn("DEV redesign layer", response.text)
        self.assertIn("body.dev-console", response.text)
        self.assertIn(".app-frame", response.text)
        self.assertIn(".data-grid", response.text)
        self.assertIn(".workspace.is-wide-mode", response.text)
        self.assertIn(".workspace.is-qa-mode", response.text)
        self.assertIn(".qa-layout", response.text)
        self.assertIn(".faq-panel", response.text)
        self.assertIn(".faq-item.is-open", response.text)
        self.assertIn(".impact-cell", response.text)
        self.assertIn("#landing-table", response.text)
        self.assertIn(".guide-tab.is-active", response.text)
        self.assertIn(".dev-slide-card", response.text)
        self.assertIn(".dev-guide-field-table", response.text)
        self.assertIn(".dev-copy-guide-table", response.text)
        self.assertIn(".dev-pixel-event-grid", response.text)
        self.assertIn(".dev-guide-code-grid", response.text)
        self.assertIn(".dev-slide-grid.material", response.text)
        self.assertIn(".dev-slide-pills", response.text)
        self.assertIn(".dev-card-code", response.text)
        self.assertIn("overflow: visible", response.text)
        self.assertIn("print-color-adjust: exact !important", response.text)
        self.assertIn("background: #111827 !important", response.text)
        self.assertIn("body.dev-guide-print", response.text)
        self.assertIn(".repeat-block.is-collapsed > .repeat-body", response.text)
        self.assertIn("--block-accent", response.text)
        self.assertIn(".block-sequence", response.text)
        self.assertIn(".workbook-notice", response.text)
        self.assertIn(".review-overlay", response.text)
        self.assertIn(".review-table", response.text)
        self.assertIn(".analytics-chart-grid", response.text)
        self.assertIn(".analytics-table-grid", response.text)
        self.assertIn(".question-category.is-open", response.text)
        self.assertIn(".notice-editor-shell", response.text)
        self.assertIn(".notice-toolbar", response.text)
        self.assertIn(".notice-preview-surface", response.text)
        self.assertIn(".guide-admin-deck", response.text)
        self.assertIn(".guide-editable-text", response.text)
        self.assertIn(".guide-admin-actions", response.text)
        self.assertIn(".admin-guide-slide-tools", response.text)
        self.assertIn(".admin-guide-card-action", response.text)
        self.assertIn(".admin-guide-image-tools", response.text)
        self.assertIn(".admin-guide-upload-status", response.text)
        self.assertIn(".list-toolbar", response.text)
        self.assertIn(".list-pagination", response.text)
        self.assertIn(".row-actions", response.text)
        self.assertIn(".ads-key-table", response.text)
        self.assertIn(".button-spinner", response.text)
        self.assertIn("@keyframes button-spin", response.text)

    def test_dev_assets_do_not_expose_copied_html_pages(self) -> None:
        client = TestClient(app)

        response = client.get("/dev-assets/index.html")

        self.assertEqual(response.status_code, 404)


if __name__ == "__main__":
    unittest.main()
