from __future__ import annotations

import unittest

from fastapi.testclient import TestClient

from app import app


class DevRoutesStaticTests(unittest.TestCase):
    def test_dev_redesign_routes_are_available(self) -> None:
        client = TestClient(app)

        routes = {
            "/dev": "OpenAI Ads 운영 도구",
            "/dev/admin": "OpenAI Ads 관리자",
            "/dev/creative-upload-draft": "소재 접수 및 업로드 파일 생성",
        }
        for path, phrase in routes.items():
            with self.subTest(path=path):
                response = client.get(path)
                self.assertEqual(response.status_code, 200)
                self.assertIn(phrase, response.text)
                self.assertIn('/dev-assets/dev-redesign.css', response.text)
                self.assertIn("@tabler/core", response.text)

    def test_menu_settings_api_controls_public_visibility(self) -> None:
        client = TestClient(app)
        headers = {"x-admin-password": "nas2026@"}

        self.assertEqual(client.get("/api/admin/menu-settings").status_code, 403)
        public_response = client.get("/api/menu-settings")
        self.assertEqual(public_response.status_code, 200)
        self.assertIn("menus", public_response.json())
        self.assertIn("guide_decks", public_response.json())
        original_settings = client.get("/api/admin/menu-settings", headers=headers).json()

        try:
            response = client.post(
                "/api/admin/menu-settings",
                headers=headers,
                json={
                    "menus": {"qa": False, "landing": True, "favicon": True, "guides": True, "creative": False},
                    "guide_decks": {"advertiser": True, "setup": False, "pixel": False},
                },
            )
            self.assertEqual(response.status_code, 200)
            payload = response.json()
            self.assertFalse(payload["menus"]["qa"])
            self.assertFalse(payload["menus"]["creative"])
            self.assertFalse(payload["guide_decks"]["setup"])

            public_payload = client.get("/api/menu-settings").json()
            self.assertFalse(public_payload["menus"]["qa"])
            self.assertFalse(public_payload["guide_decks"]["pixel"])
        finally:
            client.post("/api/admin/menu-settings", headers=headers, json=original_settings)

    def test_menu_settings_fail_closed_until_api_loads(self) -> None:
        client = TestClient(app)
        pages = [client.get("/").text, client.get("/dev").text]
        css = client.get("/dev-assets/dev-redesign.css").text

        for page in pages:
            with self.subTest("initial menu gate"):
                self.assertIn('class="dev-console menu-settings-pending"', page)
                self.assertIn("state.menuSettingsLoaded = false", page)
                self.assertIn("if (!state.menuSettingsLoaded) return false", page)
                self.assertIn('document.body.classList.remove("menu-settings-pending")', page)
                self.assertIn("state.menuSettingsLoaded && (isEnabled || admin)", page)

        self.assertIn("body.menu-settings-pending [data-menu-key]", css)
        self.assertIn("body.menu-settings-pending [data-guide-deck]", css)

    def test_dev_pages_use_new_command_center_markup(self) -> None:
        client = TestClient(app)

        home = client.get("/dev").text
        public_home = client.get("/").text
        admin = client.get("/dev/admin").text
        intake = client.get("/dev/creative-upload-draft").text

        for page in (home, admin, intake):
            self.assertIn('id="global-loading"', page)
            self.assertIn("setGlobalLoading", page)
            self.assertIn("loadingMessage", page)

        self.assertIn('class="app-frame"', home)
        self.assertIn('id="entry-notice"', home)
        self.assertIn('id="entry-notice-content"', home)
        self.assertIn('id="entry-notice-skip"', home)
        self.assertIn("오늘 더 이상 보지 않기", home)
        self.assertIn("/api/notice", home)
        self.assertIn("initEntryNotice", home)
        self.assertIn('data-view-button="qa"', home)
        self.assertIn('data-menu-key="qa"', home)
        self.assertIn('data-menu-key="creative"', home)
        self.assertIn("/api/menu-settings", home)
        self.assertIn("loadMenuSettings", home)
        self.assertIn("is-admin-visible-disabled", home)
        self.assertIn("URL 점검", home)
        self.assertIn("이미지 점검", home)
        self.assertIn("GUIDE", home)
        self.assertIn('class="status-indicator is-on"', home)
        self.assertIn('href="/dev/creative-upload-draft"', home)
        self.assertNotIn('data-admin-required-link', home)
        self.assertNotIn('data-admin-href="/dev/creative-upload-draft"', home)
        self.assertIn("updateAdminGatedLinks", home)
        self.assertNotIn("관리자 로그인 후 소재 접수 메뉴를 사용할 수 있습니다.", home)
        self.assertIn("OpenAI Ads 운영 센터", home)
        self.assertIn("소재 접수 베타", home)
        self.assertIn("sourceTierMeta", home)
        self.assertIn("sourceChipMarkup", home)
        self.assertIn("tag tag-amber", home)
        self.assertIn("답변 생성에 실패했습니다. 잠시 후 다시 시도", home)
        self.assertIn('id="workspace-layout"', home)
        self.assertIn("is-wide-mode", home)
        self.assertIn("faqCategories", home)
        self.assertIn("광고 정책 및 운영 FAQ", home)
        self.assertIn("Account Spend Cap", home)
        self.assertIn("renderFaq", home)
        self.assertNotIn("loadFaqs", home)
        self.assertNotIn("/api/faqs", home)
        self.assertIn("qa-input-panel", home)
        self.assertIn("data-faq-category", home)
        self.assertIn("data-faq-id", home)
        self.assertIn("캠페인 영향", home)
        self.assertIn("landingCampaignImpact", home)
        self.assertIn("faviconCampaignImpact", home)
        self.assertIn("campaign_impact", home)
        self.assertIn("guide-tabs", home)
        self.assertIn("data-guide-deck=\"advertiser\"", home)
        self.assertIn("data-guide-deck=\"setup\"", home)
        self.assertIn("data-guide-deck=\"pixel\"", home)
        self.assertIn("dev-slide-deck", home)
        self.assertIn("printCurrentGuideDeck", home)
        self.assertIn("applyGuideLayout", home)
        self.assertIn("hasUsableGuideLayout", home)
        self.assertIn("guideUsesSavedLayout", home)
        self.assertIn("tagProductionGuideTextKeys", home)
        self.assertIn("reconcileProductionGuideStructure", home)
        self.assertIn("createGuideTextPairElement", home)
        self.assertIn("applyGuideTextValue", home)
        self.assertIn("normalizeGuidePairClass", home)
        self.assertIn("reconcileProductionGuideStructure(state.guideDeck);", home)
        self.assertIn("normalizeGuideDeckEditKeys(guideDeckDefaults);", home)
        self.assertIn("normalizeGuideDeckEditKeys(guideDeckDefaults);", public_home)
        self.assertIn("applyGuideTextValue", public_home)
        self.assertIn("normalizeGuidePairClass", public_home)
        self.assertIn("reconcileProductionGuideStructure(state.guideDeck);", public_home)
        self.assertIn("copyGuide.columnKeys", public_home)
        self.assertIn("copyGuide.rowKeys", public_home)
        self.assertIn(".copy-guide-table, .dev-copy-guide-table", public_home)
        self.assertIn("state.guideDeckHtml = new Map(Object.entries(deckHtml.decks || {}));", home)
        self.assertIn("guideDeckDefaults", home)
        self.assertIn("guide-public-slide", home)
        self.assertIn("densityClass", home)
        self.assertIn("is-long", home)
        self.assertNotIn('index >= 5) element.classList.add("split")', home)
        self.assertNotIn('index >= 5) element.classList.add("split")', public_home)
        self.assertIn("GUIDE_LAYOUT_VERSION = 5", home)
        self.assertIn("GUIDE_LAYOUT_FINGERPRINT", home)
        self.assertIn("광고 카피 작성 가이드", home)
        self.assertIn("플래너에게 받아야 할 캠페인 정보 및 소재", home)
        self.assertIn("OpenAI 공식 워크북 기준", home)
        self.assertIn("정식 오픈 시 Ads Manager 재확인", home)
        self.assertIn("dev-card-code", home)
        self.assertIn("campaign_preview", home)
        self.assertIn("STEP 3-C · 맞춤 이벤트 & QA", home)
        self.assertIn("pixel_step6_event_list", home)
        self.assertIn("GTM 컨테이너 ID", home)
        self.assertIn('id="admin-app"', admin)
        self.assertIn('data-admin-view="menuSettings"', admin)
        self.assertIn('id="admin-view-menuSettings"', admin)
        self.assertIn('id="menu-settings-form"', admin)
        self.assertIn('id="guide-deck-settings-form"', admin)
        self.assertIn('id="save-menu-settings"', admin)
        self.assertIn("menu-save-button", admin)
        self.assertIn("coerceMenuSetting", admin)
        self.assertIn("syncMenuToggleCards", admin)
        self.assertIn("menuSettingsLoaded", admin)
        self.assertIn("메뉴 설정을 먼저 불러온 뒤 저장해 주세요.", admin)
        self.assertIn("/api/admin/menu-settings", admin)
        self.assertIn("관리자 세션에서는 비활성 메뉴도 검수용으로 계속 접근", admin)
        self.assertIn("echarts@5", admin)
        self.assertIn('id="notice-toolbar"', admin)
        self.assertIn('id="notice-editor"', admin)
        self.assertIn('contenteditable="true"', admin)
        self.assertIn("data-notice-command", admin)
        self.assertIn("data-notice-format", admin)
        self.assertIn("data-notice-template", admin)
        self.assertIn('id="notice-preview-body"', admin)
        self.assertNotIn('id="notice-body"', admin)
        self.assertNotIn("본문 HTML", admin)
        self.assertIn('id="analytics-period"', admin)
        self.assertIn("analytics-chart-grid", admin)
        self.assertIn('id="visit-pie-chart"', admin)
        self.assertIn('id="analytics-page-rows"', admin)
        self.assertIn('id="analytics-download-rows"', admin)
        self.assertIn("질문 카테고리", admin)
        self.assertIn('id="question-category-list"', admin)
        self.assertIn('id="metric-questions"', admin)
        self.assertIn('id="question-page-prev"', admin)
        self.assertIn('id="question-page-next"', admin)
        self.assertIn("data-question-category", admin)
        self.assertIn("mail-review-table", admin)
        self.assertIn("메일 원문", admin)
        self.assertIn("지식 반영안", admin)
        self.assertIn("mail-source-text", admin)
        self.assertIn("mail-rag-draft", admin)
        self.assertIn("faqDraftFromMail", admin)
        self.assertIn("approved_summary: approvedSummary", admin)
        self.assertIn("readonly", admin)
        self.assertIn("메일 원문은 증거 자료로 잠겨 있습니다.", admin)
        self.assertIn('id="manual-rag-create"', admin)
        self.assertIn('id="admin-view-manualRag"', admin)
        self.assertIn("/api/admin/manual-rag", admin)
        self.assertIn('select class="control" id="manual-rag-category"', admin)
        self.assertIn("RAG 운영 지식 직접 등록", admin)
        self.assertIn("FAQ에는 자동 추가되지 않습니다", admin)
        self.assertIn("MANUAL_RAG_CATEGORIES", admin)
        for category in [
            "계정·런칭",
            "입찰·예산",
            "청구·세금",
            "롤아웃·인벤토리",
            "랜딩·크롤러",
            "정책·제한업종",
            "전환·권한",
            "플랫폼·지원",
        ]:
            self.assertIn(category, admin)
        self.assertIn('id="mail-prev"', admin)
        self.assertIn('id="mail-next"', admin)
        self.assertIn('id="mail-page-info"', admin)
        self.assertIn("MAIL_REVIEW_PAGE_SIZE = 10", admin)
        self.assertIn("최근 ${retentionDays}일 메일", admin)
        self.assertIn("14일 초과", admin)
        self.assertIn('data-admin-view="faqManager"', admin)
        self.assertIn('id="admin-view-faqManager"', admin)
        self.assertIn('id="faq-category-admin-list"', admin)
        self.assertIn('id="faq-item-admin-list"', admin)
        self.assertIn("/api/admin/faqs/categories", admin)
        self.assertIn("/api/admin/faqs/items", admin)
        self.assertIn("FAQ는 RAG와 별도로 관리됩니다.", admin)
        self.assertIn('id="official-start-date"', admin)
        self.assertIn('id="official-end-date"', admin)
        self.assertIn('id="official-clear-period"', admin)
        self.assertIn('id="official-refresh"', admin)
        self.assertIn('id="official-prev"', admin)
        self.assertIn('id="official-next"', admin)
        self.assertIn('id="official-page-info"', admin)
        self.assertIn("한 페이지에 15개씩 표시합니다.", admin)
        self.assertIn("RAG 검색에는 요약이 아니라 수집된 원문 본문이 청크 단위로 반영", admin)
        self.assertIn('OFFICIAL_PAGE_SIZE = 15', admin)
        self.assertIn('page: String(officialPage)', admin)
        self.assertIn('id="admin-guide-tabs"', admin)
        self.assertIn('id="admin-guide-deck"', admin)
        self.assertIn("data-admin-guide-deck=\"advertiser\"", admin)
        self.assertIn("data-admin-guide-deck=\"setup\"", admin)
        self.assertIn("data-admin-guide-deck=\"pixel\"", admin)
        self.assertIn("adminGuideDecks", admin)
        self.assertIn("normalizeAdminGuideDeckEditKeys", admin)
        self.assertIn("guide-editable-text", admin)
        self.assertIn("data-guide-text-key", admin)
        self.assertIn("copyGuide.titleKey", admin)
        self.assertIn("copyGuide.columnKeys", admin)
        self.assertIn("copyGuide.rowKeys", admin)
        self.assertIn("테이블 헤더", admin)
        self.assertIn("data-guide-image-key", admin)
        self.assertIn('id="add-admin-guide-slide"', admin)
        self.assertIn("편집 전용 보기입니다.", admin)
        self.assertIn("관리 편의를 위해 슬라이드가 콘텐츠 높이만큼 세로로 길게 펼쳐집니다.", admin)
        self.assertIn('data-guide-action="add-card"', admin)
        self.assertIn('data-guide-action="remove-card"', admin)
        self.assertIn('data-guide-action="move-slide-up"', admin)
        self.assertIn('data-guide-action="move-slide-down"', admin)
        self.assertIn('data-guide-action="remove-slide"', admin)
        self.assertIn("guideLayoutPayload", admin)
        self.assertIn("applyAdminGuideLayout", admin)
        self.assertIn("collectGuidePayloadKeys", admin)
        self.assertIn("hydrateGuidePayloadItems", admin)
        self.assertIn("GUIDE_LAYOUT_VERSION = 5", admin)
        self.assertIn("GUIDE_LAYOUT_FINGERPRINT", admin)
        self.assertIn("광고 카피 작성 가이드", admin)
        self.assertIn("플래너에게 받아야 할 캠페인 정보 및 소재", admin)
        self.assertIn("OpenAI 공식 워크북 기준", admin)
        self.assertIn("정식 오픈 시 Ads Manager 재확인", admin)
        self.assertIn("STEP 3-C · 맞춤 이벤트 & QA", admin)
        self.assertIn("pixel_step6_event_list", admin)
        self.assertIn("codeBlocks", admin)
        self.assertIn("kickerKey", admin)
        self.assertNotIn("이미지 URL 교체", admin)
        self.assertNotIn("admin-guide-image-url", admin)
        self.assertIn("admin-guide-image-file", admin)
        self.assertIn("uploadGuideImageFile", admin)
        self.assertIn("/api/admin/guide-image", admin)
        self.assertIn("setButtonBusy", admin)
        self.assertIn("button-spinner", admin)
        self.assertIn("안내자료 저장이 완료되었습니다.", admin)
        self.assertIn("readGuidePayload", admin)
        self.assertNotIn('id="guide-item-editor"', admin)
        self.assertNotIn('id="guide-image-editor"', admin)
        self.assertIn('id="ads-key-search"', admin)
        self.assertIn('id="ads-key-sort"', admin)
        self.assertIn('id="ads-key-prev"', admin)
        self.assertIn('id="ads-key-next"', admin)
        self.assertIn('id="cancel-ads-edit"', admin)
        self.assertIn('id="ads-industry"', admin)
        self.assertIn('id="inspect-ads-key"', admin)
        self.assertIn('id="ads-key-preview"', admin)
        self.assertIn('id="conversion-key-preview"', admin)
        self.assertIn("/api/admin/ads-api-keys/inspect", admin)
        self.assertIn("/reveal", admin)
        self.assertIn("ADS_KEY_PAGE_SIZE = 10", admin)
        self.assertIn("ADS_INDUSTRIES", admin)
        self.assertIn('<option value="패션">패션</option>', admin)
        self.assertIn('<option value="화장품">화장품</option>', admin)
        self.assertIn('<option value="수송">수송</option>', admin)
        self.assertNotIn("패션/화장품", admin)
        self.assertIn("renderAdsKeyRows", admin)
        self.assertIn("editAdsKey", admin)
        self.assertIn("deleteAdsKey", admin)
        self.assertIn('data-ads-action="edit"', admin)
        self.assertIn('data-ads-action="delete"', admin)
        self.assertIn('data-admin-view="adcopyGenerator"', admin)
        self.assertIn('id="admin-view-adcopyGenerator"', admin)
        self.assertIn("AI 카피 생성기", admin)
        self.assertIn('id="adcopy-generator-form"', admin)
        self.assertIn('id="generate-adcopy"', admin)
        self.assertIn('id="fill-adcopy-sample"', admin)
        self.assertIn('id="copy-adcopy-json"', admin)
        self.assertIn('id="download-adcopy-json"', admin)
        self.assertIn('id="download-adcopy-csv"', admin)
        self.assertIn('id="download-adcopy-report"', admin)
        self.assertIn('id="validate-adcopy-json"', admin)
        self.assertIn('id="apply-adcopy-auto-review"', admin)
        self.assertIn('id="reset-adcopy-review-status"', admin)
        self.assertIn("/api/admin/adcopy/generate", admin)
        self.assertIn("/api/admin/adcopy/validate", admin)
        self.assertIn("/api/admin/adcopy/inspect-landing", admin)
        self.assertIn('id="inspect-adcopy-landing"', admin)
        self.assertIn('id="adcopy-landing-insight"', admin)
        self.assertIn("generated.json 보기", admin)
        self.assertIn('id="adcopy-brief-meter"', admin)
        self.assertIn("브리프 완성도", admin)
        self.assertIn("브리프 보강", admin)
        self.assertIn('data-adcopy-preset="industry"', admin)
        self.assertIn("renderAdcopyBriefMeter", admin)
        self.assertIn("applyAdcopyBriefPreset", admin)
        self.assertIn("applyAdcopySampleBrief", admin)
        self.assertIn("ADCOPY_SAMPLE_BRIEFS", admin)
        self.assertIn("adcopyIndustryPresetLines", admin)
        self.assertIn('id="adcopy-quality-panel"', admin)
        self.assertIn('id="adcopy-upload-checklist"', admin)
        self.assertIn("품질 스코어", admin)
        self.assertIn("renderAdcopyQualityPanel", admin)
        self.assertIn("renderAdcopyUploadChecklist", admin)
        self.assertIn('data-adcopy-preview-filter="issue"', admin)
        self.assertIn('id="adcopy-review-filter"', admin)
        self.assertIn("setAdcopyPreviewFilter", admin)
        self.assertIn("setAdcopyReviewFilter", admin)
        self.assertIn("adcopyPreviewFilterCounts", admin)
        self.assertIn("adcopyReviewFilterCounts", admin)
        self.assertIn("adcopyReviewStatusMatches", admin)
        self.assertIn("handleAdcopyEdit", admin)
        self.assertIn("adcopyLengthMeta", admin)
        self.assertIn("adcopyTrace", admin)
        self.assertIn("renderAdcopyReviewControls", admin)
        self.assertIn("applyAdcopyAutoReview", admin)
        self.assertIn("resetAdcopyReviewStatus", admin)
        self.assertIn('data-adcopy-review="validation_status"', admin)
        self.assertIn("adcopyFindingAdIndex", admin)
        self.assertIn("focusAdcopyCreative", admin)
        self.assertIn("data-adcopy-focus-index", admin)
        self.assertIn("setAdcopyFieldIssue", admin)
        self.assertIn("focusFirstAdcopyFieldIssue", admin)
        self.assertIn("validateEditedAdcopy", admin)
        self.assertIn("downloadAdcopyJson", admin)
        self.assertIn("downloadAdcopyCreativeCsv", admin)
        self.assertIn("buildAdcopyCreativeCsv", admin)
        self.assertIn("downloadAdcopyReviewReport", admin)
        self.assertIn("OpenAI Ads AI 카피 검수 리포트", admin)
        self.assertIn("inspectAdcopyLanding", admin)
        self.assertIn("renderAdcopyResult", admin)
        self.assertIn("ADCOPY_DEFAULT_BANNED_TERMS", admin)
        self.assertIn('data-admin-view="performance"', admin)
        self.assertIn('id="admin-view-performance"', admin)
        self.assertIn("Ads API 성과 대시보드", admin)
        self.assertIn('id="performance-advertiser-select"', admin)
        self.assertIn("전체 활성 광고주", admin)
        self.assertIn('id="performance-campaign-rows"', admin)
        self.assertIn('id="performance-detail-rows"', admin)
        self.assertIn('id="performance-device-chart"', admin)
        self.assertIn('id="performance-volume-trend"', admin)
        self.assertIn('id="performance-spend-trend"', admin)
        self.assertIn('id="performance-benchmark-rows"', admin)
        self.assertIn('id="performance-extension-note"', admin)
        self.assertIn('id="performance-campaign-prev"', admin)
        self.assertIn('id="performance-benchmark-prev"', admin)
        self.assertIn('id="performance-detail-prev"', admin)
        self.assertIn('id="download-performance-campaigns"', admin)
        self.assertIn('id="download-performance-include-campaigns"', admin)
        self.assertIn('id="download-performance-include-adgroups"', admin)
        self.assertIn('id="download-performance-include-ads"', admin)
        self.assertIn('id="download-performance-benchmarks"', admin)
        self.assertIn('id="performance-live-advertisers"', admin)
        self.assertIn('id="performance-live-campaigns"', admin)
        self.assertIn("performance-status-card", admin)
        self.assertIn('id="performance-campaign-table"', admin)
        self.assertIn("예산/소진", admin)
        self.assertIn("budgetSpendMarkup", admin)
        self.assertIn("formatBudgetRate", admin)
        self.assertIn("campaignBudgetBasis", admin)
        self.assertIn("groupBudgetSpendSummary", admin)
        self.assertIn("기간 예산", admin)
        self.assertIn("analyzePerformanceHourlyBudget", admin)
        self.assertIn("PERFORMANCE_EARLY_DEPLETION_HOUR", admin)
        self.assertIn("00~03시 소진 비중", admin)
        self.assertIn("증액 제안 후보", admin)
        self.assertIn('data-performance-sort="name"', admin)
        self.assertIn('data-performance-sort="advertiser_name"', admin)
        self.assertIn('data-performance-sort="industry"', admin)
        self.assertIn('data-benchmark-mode="objective"', admin)
        self.assertIn("data-performance-advertiser-toggle", admin)
        self.assertIn("data-performance-campaign-toggle", admin)
        self.assertIn("data-performance-adgroup-toggle", admin)
        self.assertIn('id="toggle-performance-conversions"', admin)
        self.assertIn("performanceLiveAdvertiserNames", admin)
        self.assertIn("performanceAdvertiserStatusLabel", admin)
        self.assertIn("performanceDashboardStatusMessage", admin)
        self.assertIn("performanceCacheStatusLabel", admin)
        self.assertIn("fetchPerformanceNestedDetail", admin)
        self.assertIn("PERFORMANCE_CAMPAIGN_COLSPAN = 17", admin)
        self.assertIn("전체 활성 광고주(${formatNumber(activeAdvertisers.length)})", admin)
        self.assertIn("cache_note", admin)
        self.assertNotIn("campaign-id", admin)
        self.assertIn("disposePerformanceTrendCharts", admin)
        self.assertIn("renderPerformanceDeviceChart", admin)
        self.assertIn("renderPerformanceVolumeChart", admin)
        self.assertIn("renderPerformanceCostChart", admin)
        self.assertIn("downloadPerformanceCampaigns", admin)
        self.assertIn("loadPerformanceDetailForScope", admin)
        self.assertIn("selectedPerformanceDownloadScope", admin)
        self.assertIn("sortedPerformanceCampaignRows", admin)
        self.assertIn("groupedPerformanceCampaignRows", admin)
        self.assertIn("renderPerformanceTrend", admin)
        self.assertIn("padPerformanceTrendRows", admin)
        self.assertIn("renderPerformanceBenchmarks", admin)
        self.assertIn("downloadPerformanceBenchmarks", admin)
        self.assertIn("loadPerformanceDashboard", admin)
        self.assertIn("/api/admin/ads-dashboard", admin)
        self.assertIn("renderPerformanceKpis", admin)
        self.assertIn("performance-kpi-grid", admin)
        self.assertIn('data-admin-view="campaignIntakes"', admin)
        self.assertIn('id="admin-view-campaignIntakes"', admin)
        self.assertIn('id="campaign-intake-list"', admin)
        self.assertIn('id="campaign-intake-search"', admin)
        self.assertIn('id="campaign-intake-status-filter"', admin)
        self.assertIn("캠페인 접수 현황", admin)
        self.assertIn("renderCampaignIntakeList", admin)
        self.assertIn("loadCampaignIntakes", admin)
        self.assertIn("saveCampaignIntakeOps", admin)
        self.assertIn("intakeCopyButton", admin)
        self.assertIn("intakeValueCell", admin)
        self.assertIn("copyTextToClipboard", admin)
        self.assertIn("data-intake-value", admin)
        self.assertIn("campaign-intake-header", admin)
        self.assertIn("campaign-intake-record", admin)
        self.assertIn("intake-toggle", admin)
        self.assertIn("intake-toggle-label", admin)
        self.assertIn("intake-kv-table", admin)
        self.assertIn('<option value="ready">대기</option>', admin)
        self.assertIn('<option value="canceled">취소</option>', admin)
        self.assertIn("운영 메모", admin)
        self.assertIn("intakeSubmittedAtDisplay", admin)
        self.assertIn("campaign-intake-inline-control", admin)
        self.assertNotIn('data-intake-copy="receipt"', admin)
        self.assertNotIn("intakeValue(campaign.campaign_name", admin)
        self.assertNotIn("intakeValue(adgroup.adgroup_name", admin)
        self.assertNotIn("intakeValue(ad.ad_name", admin)
        self.assertNotIn("campaign-intake-meta", admin)
        self.assertNotIn("campaign-intake-ops", admin)
        self.assertNotIn('data-intake-action="save"', admin)
        self.assertNotIn("<span>구조</span>", admin)
        self.assertNotIn("<span>비고</span>", admin)
        self.assertIn("/api/admin/campaign-intakes", admin)
        self.assertIn("/api/admin/campaign-intakes/update", admin)
        self.assertIn('id="campaign-template"', intake)
        self.assertIn('id="adgroup-template"', intake)
        self.assertIn("수동 국가", intake)
        self.assertIn("캠페인 입력 요약", intake)
        self.assertIn("광고그룹 입력 요약", intake)
        self.assertIn("소재 입력 요약", intake)
        self.assertIn("campaign_name 자동 참조", intake)
        self.assertIn("adgroup_name 자동 참조", intake)
        self.assertIn("summary-ad-name", intake)
        self.assertIn("summary-ad-link", intake)
        self.assertIn("file-upload-card", intake)
        self.assertIn("workbook-file-name", intake)
        self.assertIn("워크북 파일 선택", intake)
        self.assertIn("creative-intake-page", intake)
        self.assertIn("creative-intake-footer", intake)
        self.assertIn("OpenAI Ads Creative Intake", intake)
        self.assertIn("수동 입찰가", intake)
        self.assertIn("campaign-manual-country", intake)
        self.assertIn("adgroup-manual-bid", intake)
        self.assertIn("collapse-toggle", intake)
        self.assertIn('class="btn-plain add-campaign"', intake)
        self.assertIn('class="btn-plain add-adgroup"', intake)
        self.assertIn('class="btn-plain add-ad"', intake)
        self.assertIn("소재그룹 추가", intake)
        self.assertIn("insertAfter.after", intake)
        self.assertIn("campaign-sequence", intake)
        self.assertIn("adgroup-sequence", intake)
        self.assertIn("ad-sequence", intake)
        self.assertIn("campaignThemes", intake)
        self.assertIn("applyCampaignTheme", intake)
        self.assertIn("validateNameFields", intake)
        self.assertIn("validateDerivedFields", intake)
        self.assertIn("캠페인 1", intake)
        self.assertIn("광고그룹 1-1", intake)
        self.assertIn("소재 1-1-1", intake)
        self.assertIn("workbook-notice", intake)
        self.assertIn("다운로드한 XLSX는 OpenAI Ads Manager 벌크 업로드 기준 파일입니다.", intake)
        self.assertIn("serverErrorMessage", intake)
        self.assertIn("isSafeWorkbookName", intake)
        self.assertIn("isHttpUrl", intake)
        self.assertIn("campaignBlocks().map(readCampaign)", intake)
        self.assertIn("data-reference-static", intake)
        self.assertIn("한글, 영문, 숫자", intake)
        self.assertIn("review-overlay", intake)
        self.assertIn("구글 시트에 저장할 내용을 확인해 주세요", intake)
        self.assertIn("openReviewModal(payload())", intake)
        self.assertIn("manual_target_country", intake)
        self.assertIn("manual_target_country_label", intake)
        self.assertIn("manual_max_bid", intake)
        self.assertIn("수동 입찰가(KRW)", intake)
        self.assertIn("submitReviewedPayload", intake)
        self.assertIn("pendingSubmissionPayload", intake)
        self.assertIn("required-mark", intake)
        self.assertIn("Ads Manager Reference", intake)
        self.assertIn("실제 세팅 창 참고", intake)
        self.assertIn("표준 캠페인", intake)
        self.assertIn("제품피드 캠페인", intake)
        self.assertIn("아직 비활성", intake)
        self.assertIn("제품 피드 ID", intake)
        self.assertIn("새 캠페인 · 캠페인 만들기", intake)
        self.assertIn("광고그룹 만들기", intake)
        self.assertIn("광고 만들기 · 광고 소재", intake)
        self.assertIn("전환 이벤트(선택 사항)", intake)
        self.assertIn("종료일 설정", intake)
        self.assertIn("다음: 광고 그룹", intake)
        self.assertIn("최대 CPC 입찰가", intake)
        self.assertIn("컨텍스트 힌트", intake)
        self.assertIn("광고 이미지", intake)
        self.assertIn('<option value="ALL">전체</option>', intake)
        self.assertIn('<option value="US">미국</option>', intake)
        self.assertIn('<option value="AU">오스트레일리아</option>', intake)
        self.assertIn('<option value="CA">캐나다</option>', intake)
        self.assertIn('<option value="JP">일본</option>', intake)
        self.assertIn('<option value="NZ">뉴질랜드</option>', intake)
        self.assertIn('<option value="KR">대한민국</option>', intake)
        self.assertIn('<option value="GB">영국</option>', intake)
        self.assertNotIn("Ads Manager 계정 준비", intake)
        self.assertNotIn("정산 정보 확인", intake)
        self.assertNotIn("랜딩 접근 확인", intake)
        self.assertNotIn("로고·파비콘 확인", intake)
        self.assertNotIn("대한민국은 수동 세팅에서는 선택하고", intake)
        self.assertNotIn("xlsx target_countries", intake)
        self.assertNotIn("xlsx max_bid", intake)
        self.assertNotIn('id="add-campaign"', intake)
        self.assertNotIn('$("#add-campaign")', intake)

    def test_dev_redesign_css_asset_is_available(self) -> None:
        client = TestClient(app)

        response = client.get("/dev-assets/dev-redesign.css")

        self.assertEqual(response.status_code, 200)
        self.assertIn("text/css", response.headers.get("content-type", ""))
        self.assertIn("OpenAI Ads console UI layer", response.text)
        self.assertIn("body.dev-console", response.text)
        self.assertIn(".app-frame", response.text)
        self.assertIn(".data-grid", response.text)
        self.assertIn(".workspace.is-wide-mode", response.text)
        self.assertIn(".workspace.is-qa-mode", response.text)
        self.assertIn(".qa-layout", response.text)
        self.assertIn(".qa-input-panel", response.text)
        self.assertIn("position: sticky", response.text)
        self.assertIn(".faq-panel", response.text)
        self.assertIn(".faq-item.is-open", response.text)
        self.assertIn(".impact-cell", response.text)
        self.assertIn("#landing-table", response.text)
        self.assertIn(".guide-tab.is-active", response.text)
        self.assertIn(".dev-slide-card", response.text)
        self.assertIn(".dev-slide-card.guide-public-slide", response.text)
        self.assertIn(".dev-slide-grid .dev-slide-item.is-long", response.text)
        self.assertIn(".dev-slide-deck .guide-text-preserve-lines", response.text)
        self.assertIn(".dev-slide-deck .slide-card.ad-material-slide .slide-item.is-long", response.text)
        self.assertIn("body.dev-guide-print .dev-slide-card.guide-public-slide", response.text)
        self.assertIn(".dev-guide-field-table", response.text)
        self.assertIn(".dev-copy-guide-table", response.text)
        self.assertIn(".dev-pixel-event-grid", response.text)
        self.assertIn(".dev-guide-code-grid", response.text)
        self.assertIn(".dev-slide-grid.material", response.text)
        self.assertIn(".dev-slide-pills", response.text)
        self.assertIn(".dev-card-code", response.text)
        self.assertIn(".campaign-intake-record", response.text)
        self.assertIn(".campaign-intake-summary", response.text)
        self.assertIn("white-space: nowrap", response.text)
        self.assertIn(".campaign-intake-tree", response.text)
        self.assertIn(".intake-kv-table", response.text)
        self.assertIn(".intake-copy-value", response.text)
        self.assertIn(".intake-toggle-label::before", response.text)
        self.assertIn("overflow: visible", response.text)
        self.assertIn("print-color-adjust: exact !important", response.text)
        self.assertIn("background: #111827 !important", response.text)
        self.assertIn("body.dev-guide-print", response.text)
        self.assertIn(".repeat-block.is-collapsed > .repeat-body", response.text)
        self.assertIn("--block-accent", response.text)
        self.assertIn(".block-sequence", response.text)
        self.assertIn(".workbook-notice", response.text)
        self.assertIn(".review-overlay", response.text)
        self.assertIn(".review-table", response.text)
        self.assertIn(".analytics-chart-grid", response.text)
        self.assertIn(".analytics-table-grid", response.text)
        self.assertIn(".question-category-table", response.text)
        self.assertIn(".question-category-row.is-open", response.text)
        self.assertIn(".mini-pagination", response.text)
        self.assertIn(".mail-review-table", response.text)
        self.assertIn(".mail-source-text", response.text)
        self.assertIn(".mail-rag-draft", response.text)
        self.assertIn(".manual-rag-submit", response.text)
        self.assertIn(".budget-progress", response.text)
        self.assertIn(".budget-progress-track", response.text)
        self.assertIn(".budget-progress.is-over", response.text)
        self.assertIn(".hourly-recommendation-badge", response.text)
        self.assertIn(".hourly-insight-strip", response.text)
        self.assertIn(".source-chip.source-official", response.text)
        self.assertIn(".source-chip.source-internal", response.text)
        self.assertIn(".source-chip.source-pending", response.text)
        self.assertIn(".tag-amber", response.text)
        self.assertIn(".manual-rag-item", response.text)
        self.assertIn(".faq-admin-notice", response.text)
        self.assertIn(".faq-admin-grid", response.text)
        self.assertIn(".faq-admin-item", response.text)
        self.assertIn(".notice-editor-shell", response.text)
        self.assertIn(".notice-toolbar", response.text)
        self.assertIn(".notice-preview-surface", response.text)
        self.assertIn(".guide-admin-deck", response.text)
        self.assertIn(".guide-editable-text", response.text)
        self.assertIn(".guide-admin-actions", response.text)
        self.assertIn(".admin-guide-slide-tools", response.text)
        self.assertIn(".admin-guide-card-action", response.text)
        self.assertIn(".admin-guide-image-tools", response.text)
        self.assertIn(".guide-editor-notice", response.text)
        self.assertIn("grid-template-rows: auto minmax(44px, auto) auto", response.text)
        self.assertIn(".admin-guide-upload-status", response.text)
        self.assertIn("aspect-ratio: auto", response.text)
        self.assertIn("min-height: 520px", response.text)
        self.assertIn(".list-toolbar", response.text)
        self.assertIn(".official-toolbar", response.text)
        self.assertIn(".official-pagination", response.text)
        self.assertIn(".official-log-grid", response.text)
        self.assertIn(".list-pagination", response.text)
        self.assertIn(".row-actions", response.text)
        self.assertIn(".ads-key-table", response.text)
        self.assertIn(".button-spinner", response.text)
        self.assertIn("@keyframes button-spin", response.text)
        self.assertIn(".global-loading", response.text)
        self.assertIn(".global-loading-bar", response.text)
        self.assertIn(".global-loading-badge", response.text)
        self.assertIn("@keyframes global-loading-slide", response.text)
        self.assertIn(".entry-notice-overlay", response.text)
        self.assertIn(".entry-notice-modal", response.text)
        self.assertIn(".entry-notice-content", response.text)
        self.assertIn(".entry-notice-actions", response.text)
        self.assertIn(".metric .status-indicator.is-on", response.text)
        self.assertIn(".metric .status-indicator.is-off", response.text)
        self.assertIn(".admin-gated-link.is-disabled", response.text)
        self.assertIn(".rail-footer", response.text)
        self.assertIn(".creative-intake-footer", response.text)
        self.assertIn(".creative-intake-page .mapping-item strong", response.text)
        self.assertIn(".file-upload-card", response.text)
        self.assertIn(".file-upload-action", response.text)

    def test_operating_faq_api_has_public_categories(self) -> None:
        client = TestClient(app)

        response = client.get("/api/faqs")

        self.assertEqual(response.status_code, 200)
        payload = response.json()
        self.assertTrue(payload["ok"])
        self.assertIn("refresh_interval_hours", payload)
        self.assertEqual(payload["refresh_interval_hours"], 0)
        self.assertIn(payload["storage"], {"supabase", "memory"})
        categories = payload["categories"]
        self.assertEqual(len(categories), 8)
        self.assertEqual(categories[0]["id"], "account")
        self.assertLessEqual(len(categories[0]["items"]), 10)
        self.assertTrue(categories[0]["items"])
        self.assertIn("q", categories[0]["items"][0])
        self.assertIn("a", categories[0]["items"][0])
        self.assertTrue(any("Order Form" in item["q"] for item in categories[0]["items"]))
        self.assertTrue(categories[0]["items"][0]["a"])

    def test_dev_assets_do_not_expose_copied_html_pages(self) -> None:
        client = TestClient(app)

        response = client.get("/dev-assets/index.html")

        self.assertEqual(response.status_code, 404)


if __name__ == "__main__":
    unittest.main()
